config/routes.rb
Rails.application.routes.draw do

  # デバイス関係------------------------------------------------------------
  devise_for :admin, controllers: {
    sessions:      "admin/sessions",
    passwords:     "admin/passwords",
  }

  devise_for :employee, controllers: {
    sessions:      "employee/sessions",
    passwords:     "employee/passwords",
    registrations: "employee/registrations"
  }

  # ゲストログイン------------------------------------------------------------
  devise_scope :employee do
    post "/employee/guest_sign_in", to: "employee/sessions#new_guest"
  end

  # 管理者ページ----------------------------------------------------------------
  namespace :admin do
    get "top" => "homes#top", as: "top"
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :employees, only: [:index, :show, :edit, :update, :destroy]
    resources :return_comments, only: [:destroy]
    resources :manuals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  # 従業員ページ----------------------------------------------------------------
  root 'public/homes#top'

  scope module: :public do
    post "/homes/guest_sign_in", to: "homes#new_guest"
    resources :employees, only: [:show, :edit, :update]
    resources :comments do
      collection do
        get "search"
      end
    end
    resources :comments , only: [:index, :show, :create, :update, :destroy]
    resources :employees do
      resource :learnings, only: [:index]
    end
    resources :manuals do
      resource :learnings, only: [:create, :destroy, :index]
      collection do
        get "search"
      end
    end
    resources :manuals, only: [:index, :show, :create]
    resources :return_comments, only: [:index]

    get "employee/:id/learnings" => "learnings#employee_index", as: "learnings_employee"
    get "employee/:id/comments" => "comments#employee_comments", as: "comments_employee"
    get "employee/:id/comments/show" => "comments#employee_comments_show", as: "show_comments_employee"
    patch "comments/:id/is_desolved" => "comments#is_desolved", as: "is_desolved_comments"
    post " comments/return_comments_create" => "comments#return_comments_create", as: "create_return_comments"
    get "learnings/:id/is_learned" => "learnings#manual_is_learned", as: "is_learned_manual_learnings"
    patch "learnings/is_learned" => "learnings#is_rearned", as: "is_learned_learnings"
  end

end

app/models/manual.rb
class Manual < ApplicationRecord

  has_many :learnings, dependent: :destroy
  has_many :employees, through: :learnings
  has_many :comments, dependent: :destroy
  has_many :employees, through: :comments
  belongs_to :genre

  has_one_attached :video

  validates :task_name, presence: true
  validates :video, presence: true

  validate :video_size, :video_type

  def video_size
    if video.blob.byte_size > 60.megabytes
      errors.add(:video, "動画を60MG以内で撮影しなおして下さい（約３分以内）")
    end
  end

  def video_type
    if !"video".in?(video.blob.content_type)
      errors.add(:video, "はmp4またはwebm形式でアップロードしてください")
    end
  end

  def learned?(employee)
    learnings.where(employee_id: employee.id).exists?
  end

end

app/controllers/admin/manuals_controller.rb
class Admin::ManualsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @manuals = Manual.all
    @manual = Manual.new
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @manual = Manual.new
    @genres = Genre.all
  end

  def create
    @manual = Manual.new(manual_params)
    if @manual.save && @genre.sava
      redirect_to admin_manuals_path, notice: "マニュアルを投稿しました"
    else
      @manuals = Manual.all
      @genres = Genre.all
      flash[:alert] = "マニュアルの投稿に失敗しました"
      render :index
    end
  end

  def show
    @manual = Manual.find(params[:id])
    @comments = @manual.comments.all
  end

  def edit
    @manual = Manual.find(params[:id])
    @genres = Genre.all
  end

  def update
    @manual = Manual.find(params[:id])
    @genres = Genre.all
    if @manual.update(manual_params)
      redirect_to admin_manual_path(@manual), notice: "マニュアルを更新しました"
    else
      flash[:alert] = "マニュアルの更新に失敗しました"
      @manual = Manual.find(params[:id])
      render :edit
    end
  end

  def destroy
    @manual = Manual.find(params[:id])
    if @manual.destroy
      redirect_to admin_manuals_path, notice: "削除が完了しました"
    end
  end

  private

  def manual_params
    params.require(:manual).permit(:genre_name, :task_name, :description, :is_draft, :genre_id, :video, :re_draft)
  end

end

app/helpers/admin/manuals_helper.rb
module Admin::ManualsHelper
end

app/views/admin/manuals/edit.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h2 class="is-size-5-mobile">
        マニュアル編集
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">

        <%= form_with model: @manual, url: admin_manual_path, method: :patch do |f| %>

          <div class="field">
            <%= f.label :動画投稿, class: "label" %>
            <%= f.file_field :video %>
          </div>

          <div class="field">
            <%= f.label :業務名, class: "label" %>
            <%= f.select :genre_id, options_from_collection_for_select(@genres.all, :id, :name, @manual.genre_id) %>
          </div>

          <div class="field">
            <%= f.label :タスク名, class: "label" %>
            <p>
              <%= f.text_field :task_name, autofocus: true, autocomplete: "task_name", :placeholder => "例:　レジ精算の操作方法　|　日報の書き方", class: "input" %>
            </p>
          </div>

          <div class="field">
            <%= f.label :説明文, class: "label" %>
            <p>
              <%= f.text_area :description, autofocus: true, autocomplete: "description", :placeholder => "例:　レジ精算の時に出てくるレシートは捨てないでください　｜　日報を書いたら間違いがないかチェックをすること", class: "textarea", rows:"3" %>
            </p>
          </div>

          <div class="field">
            <%= f.radio_button :is_draft, "true" %>
            <%= f.label :is_draft, "下書き" %>
            <%= f.radio_button :is_draft, "false" %>
            <%= f.label :is_draft, "完了" %><br>
          </div>

          <div class="action">
            <span>
              <%= f.submit "　更新　", class: "button is-small is-success" %>
            </span>
            <span>
              <%= link_to "　削除　", admin_manual_path, data: {"turbolinks" => false} , method: :delete, data: {confirm: "本当に削除してよろしいですか？"} , class: "button is-small is-danger" %>
            </span>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/admin/manuals/index.html.erb
<%= render "layouts/error_messages", resource: @manual %>
<section class="hero is-warning">
  <!-- Hero head: will stick at the top -->
  <div class="hero-body">
    <nav class="navbar", role="navigation", aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand  columns is-desktop">
          <div class ="is-size-5-mobile column is-marginless">
            マニュアル一覧
          </div><br>
          <div class="column navbar-end">
            <div class=" navbar-end button is-primary is-inverted" data-toggle="modal" data-target="#exampleModal">
              <span class="column navbar-end">
                <i class="fa fa-camera"></i>
              </span>
              <span>マニュアル新規作成</span>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <section class="section">
        <div class="container">
          <div class="columns is-centered">
            <div class="column is-6 is-size-7-mobile">

              <%= form_with model: [@manual, @genre], url: admin_manuals_path, method: :post do |f| %>

                <div class="field">
                  <%= f.label :動画, class: "label" %>
                  <%= f.file_field :video %>
                </div>

                <div class="field">
                  <%= f.label :業務名, class: "label" %>
                  <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name) %>
                </div>

                <div class="field">
                  <%= f.label :タスク名, class: "label" %>
                  <p>
                    <%= f.text_field :task_name, autofocus: true, autocomplete: "task_name", :placeholder => "例:　レジ精算の操作方法　|　日報の書き方", class: "input" %>
                  </p>
                </div>

                <div class="field">
                  <%= f.label :説明文, class: "label" %>
                  <p>
                    <%= f.text_area :description, autofocus: true, autocomplete: "description", :placeholder => "例:　レジ精算の時に出てくるレシートは捨てないでください　｜　日報を書いたら間違いがないかチェックをすること", class: "textarea", rows:"3" %>
                  </p>
                </div>

                <div class="field">
                  <%= f.radio_button :is_draft, "true" %>
                  <%= f.label :is_draft, "下書き", value: :true %>
                  <%= f.radio_button :is_draft, "false" %>
                  <%= f.label :is_draft, "投稿", value: :false  %><br>
                </div>

                <div class="action">
                  <%= f.submit "新規登録", class: "button is-small is-success" %>
                </div>

              <% end %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">

        <table class="table is-striped is-fullwidth">
          <thead class="bg-light">
            <tr>
              <th>業務</th>
              <th>タスク</th>
              <th>更新日</th>
              <th>投稿</th>
            </tr>
          </thead>
          <% @manuals.each do |manual| %>
          <tbody>
            <tr>
              <td><%= manual.genre.name %></td>
              <td>
                <%= link_to admin_manual_path(manual.id), data: {"turbolinks" => false} do %>
                <%= manual.task_name %>
                <% end %>
              </td>
              <td><%= manual.updated_at.strftime("%Y/%m/%d") %></td>
              <td>
                <% if manual.is_draft == true %>
                  <span class="has-text-danger">
                    未
                  </span>
                <% else %>
                  <span class="has-text-primary">
                    済
                  </span>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
        </table>

      </div>
    </div>
  </div>
</section>

app/views/admin/manuals/new.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h2 class="is-size-5-mobile">
        マニュアル登録
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">

        <%= form_with model: @manual, url: admin_manuals_path, method: :post do |f| %>
        <%= render "layouts/error_messages", resource: @manual %>

          <div class="field">
            <%= f.label :動画, class: "label" %>
            <%= f.file_field :video %>
          </div>

          <div class="field">
            <%= f.label :業務名, class: "label" %>
            <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name) %>
          </div>

          <div class="field">
            <%= f.label :タスク名, class: "label" %>
            <p>
              <%= f.text_field :task_name, autofocus: true, autocomplete: "task_name", :placeholder => "例:　レジ精算の操作方法　|　日報の書き方", class: "input" %>
            </p>
          </div>

          <div class="field">
            <%= f.label :説明文, class: "label" %>
            <p>
              <%= f.text_area :description, autofocus: true, autocomplete: "description", :placeholder => "例:　レジ精算の時に出てくるレシートは捨てないでください　｜　日報を書いたら間違いがないかチェックをすること", class: "textarea", rows:"3" %>
            </p>
          </div>

          <div class="field">
            <%= f.radio_button :is_draft, "true" %>
            <%= f.label :is_draft, "下書き", value: :true %>
            <%= f.radio_button :is_draft, "false" %>
            <%= f.label :is_draft, "投稿", value: :false  %><br>
          </div>

          <div class="action">
            <%= f.submit "新規登録", class: "button is-small is-success" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/admin/manuals/show.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h2 class="is-size-5-mobile">
        <%= @manual.genre.name %>「<%= @manual.task_name %>」
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">

        <div class="field has-text-centered">
          <%= video_tag rails_blob_path(@manual.video, disposition: "atattchment"),:playsinline => true, :controls => true, :autoplay => true, :muted => true, :size => "200" %>
          <%= link_to rails_blob_path(@manual.video, disposition: "attachment"), data: {"turbolinks" => false} do %>
            <%= image_tag "download.png", alt: "Download file", :size => "100", :class => "fa fa-download" %>
          <% end %>
        </div>

        <div class="field">
          <P>
            <span>
              業務名：
            </span>
            <span>
              <%= @manual.genre.name %>
            </span>
          </P>
        </div>

        <div class="field">
          <P>
            <span>
              タスク名：
            </span>
            <span>
              <%= @manual.task_name %>
            </span>
          </P>
        </div>

        <div class="field">
          <P>
            <span>
              説明文：
            </span>
            <span>
              <%= @manual.description %>
            </span>
          </P>
        </div>

        <div class="field">
          <P>
            <% if @manual.is_draft == true %>
              <span class="is-small is-danger">
                下書き中
              </span>
            <% else %>
              <span class="is-small is-primary">
                投稿済み
              </span>
            <% end %>
          </P>
        </div>

        <div>
          <span>
            <%= link_to "編集する", edit_admin_manual_path, class: "button is-small is-success mb-3", data: {"turbolinks" => false} %>
          </span>
        </div>

        <% @comments.each do |comment| %>
          <div class="field">
            <i class="fa fa-user"></i>
            <%= comment.employee.name %>
            <span class="has-text-info">
              <%= comment.created_at.strftime("%Y/%m/%d/%H:%M") %>
            </span>
            <% if comment.is_desolved == true %>
              <span class="has-text-primary">
                ～解決済み～
              </span>
            <% else %>
              <span class="has-text-danger">
                ～未解決～
              </span>
            <% end %><br>
            <strong class="ml-3"><%= comment.comment %></strong><br>

          </div>
        <% end %>


      </div>
    </div>
  </div>
</section>