config/routes.rb
Rails.application.routes.draw do

  # デバイス関係------------------------------------------------------------
  devise_for :admin, controllers: {
    sessions:      "admin/sessions",
    passwords:     "admin/passwords",
  }

  devise_for :employee, controllers: {
    sessions:      "employee/sessions",
    passwords:     "employee/passwords",
    registrations: "employee/registrations"
  }

  # ゲストログイン------------------------------------------------------------
  devise_scope :employee do
    post "/employee/guest_sign_in", to: "employee/sessions#new_guest"
  end

  # 管理者ページ----------------------------------------------------------------
  namespace :admin do
    get "top" => "homes#top", as: "top"
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :employees, only: [:index, :show, :edit, :update, :destroy]
    resources :return_comments, only: [:destroy]
    resources :manuals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  # 従業員ページ----------------------------------------------------------------
  root 'public/homes#top'

  scope module: :public do
    post "/homes/guest_sign_in", to: "homes#new_guest"
    resources :employees, only: [:show, :edit, :update]
    resources :comments do
      collection do
        get "search"
      end
    end
    resources :comments , only: [:index, :show, :create, :update, :destroy]
    resources :employees do
      resource :learnings, only: [:index]
    end
    resources :manuals do
      resource :learnings, only: [:create, :destroy, :index]
      collection do
        get "search"
      end
    end
    resources :manuals, only: [:index, :show, :create]
    resources :return_comments, only: [:index]

    get "employee/:id/learnings" => "learnings#employee_index", as: "learnings_employee"
    get "employee/:id/comments" => "comments#employee_comments", as: "comments_employee"
    get "employee/:id/comments/show" => "comments#employee_comments_show", as: "show_comments_employee"
    patch "comments/:id/is_desolved" => "comments#is_desolved", as: "is_desolved_comments"
    post " comments/return_comments_create" => "comments#return_comments_create", as: "create_return_comments"
    get "learnings/:id/is_learned" => "learnings#manual_is_learned", as: "is_learned_manual_learnings"
    patch "learnings/is_learned" => "learnings#is_rearned", as: "is_learned_learnings"
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :learnings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :return_comments, dependent: :destroy

  validates :name, presence: true
  validates :telephone_number, presence: true

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |employee|
      employee.password = SecureRandom.alphanumeric(10) + [*'a'..'z'].sample(1).join + [*'0'..'9'].sample(1).join
      employee.name = "ゲストユーザー"
      employee.telephone_number = "09090909090"
        # employee.confirmed_ad = Time.now
    end
  end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @employees = Employee.all
    @employee = Employee.new
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      # unless @employee.is_deleted
      #   @employee.learnings.update_all(is_active: true)
      #   @employee.comments.update_all(is_active: true)
      # end
      redirect_to admin_employees_path, notice: "従業員情報を更新しました"
    else
      flash[:alert] = "従業員情報の更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.destroy
      redirect_to admin_employees_path, notice: "削除が完了しました"
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :telephone_number, :email, :password, :password_confirmation)
  end

end

app/controllers/employee/confirmations_controller.rb
# frozen_string_literal: true

class Employee::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employee/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employee::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employee/passwords_controller.rb
# frozen_string_literal: true

class Employee::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employee/registrations_controller.rb
# frozen_string_literal: true

class Employee::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの編集・削除できません"
    end
  end

  private

  def after_sign_up_path_for(resource)
    public_employee_path(current_employee)
  end

  def sign_up_params
    params.require(:employee).permit(:name, :telephone_number, :email, :password, :password_confirmation)
  end

end

app/controllers/employee/sessions_controller.rb
# frozen_string_literal: true

class Employee::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # endprivate

  def new_guest
    employee = Employee.guest
    sign_in employee
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end

  private

  def after_sign_in_path_for(resource)
    employee_path(current_employee)
  end

  def after_sign_up_path_for(resource)
    employee_path(current_employee)
  end

end

app/controllers/employee/unlocks_controller.rb
# frozen_string_literal: true

class Employee::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/views/admin/employees/edit.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h2 class="is-size-5-mobile is-centered">
        従業員情報編集
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">
        <%= form_with model: @employee, url: admin_employee_path, method: :patch do |f| %>
        <div class="field">
          <%= f.label :name, class: "label" %>
          <p class="control has-icons-left">
            <%= f.text_field :name, autofocus: true, autocomplete: "email", :placeholder => "name", class: "input" %>
            <span class="icon is-small is-left">
              <i class="fas fa-user"></i>
            </span>
          </p>
        </div>

        <div class="field">
          <%= f.label :telephone_number, class: "label" %>
          <p class="control has-icons-left">
            <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", :placeholder => "telephone_number", class: "input" %>
            <span class="icon is-small is-left">
              <i class="fas fa-phone"></i>
            </span>
          </p>
        </div>

        <div class="field">
          <%= f.label :email, class: "label" %>
          <p class="control has-icons-left">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", :placeholder => "email", class: "input" %>
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
          </p>
        </div>

        <div class="actions">
          <%= f.submit "　更新　", class: "button is-success" %>
          <%= link_to "　削除　", admin_employee_path, data: {"turbolinks" => false} , method: :delete, data: {confirm: "本当に削除してよろしいですか？"}, class: "button is-danger" %>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/admin/employees/index.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h2 class="is-size-5-mobile">
        従業員一覧
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">

        <table class="table">
          <thead class="bg-light">
            <tr>
              <th>ID</th>
              <th>氏名</th>
              <th>電話番号</th>
              <th>在籍</th>
            </tr>
          </thead>
          <% @employees.each do |employee| %>
          <tbody>
            <tr>
              <td><%= employee.id %></td>
              <td>
                <%= link_to admin_employee_path(employee.id), data: {"turbolinks" => false} do %>
                <%= employee.name %>
                <% end %>
              </td>
              <td><%= employee.telephone_number %></td>
              <% if employee.is_deleted == true %>
              <td class="text-secondary">
                退職
              </td>
              <% else %>
              <td class="text-success">
                在籍中
              </td>
              <% end %>
            </tr>
          </tbody>
          <% end %>
        </table>

      </div>
    </div>
  </div>
</section>

app/views/admin/employees/show.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h2 class="is-size-5-mobile">
        <%= @employee.name %>さんの情報
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6 is-size-7-mobile">

        <div class="field">
          <P>
            <span>
              従業員No.
            </span>
            <span>
              <%= @employee.id %>
            </span>
          </P>
        </div>

        <div class="field">
          <P>
            <span>
              氏名：
            </span>
            <span>
              <%= @employee.name %>
            </span>
            <%= link_to edit_admin_employee_path, data: {"turbolinks" => false} do %>
            <span class="icon is-small is-left">
              <i class="fas fa-edit"></i>
            </span>
            <% end %>
          </P>
        </div>

        <div class="field">
          <P>
            <span>
              電話番号：
            </span>
            <span>
              <%= @employee.telephone_number %>
            </span>
          </P>
        </div>

        <div class="field">
          <P>
            <% if @employee.is_deleted == true %>
              <span class="">
                退職
              </span>
            <% else %>
              <span class="">
                在籍中
              </span>
            <% end %>
          </P>
        </div>

      </div>
    </div>
  </div>
</section>