config/routes.rb
Rails.application.routes.draw do

  # デバイス関係------------------------------------------------------------
  devise_for :admin, controllers: {
    sessions:      "admin/sessions",
    passwords:     "admin/passwords",
  }

  devise_for :employee, controllers: {
    sessions:      "employee/sessions",
    passwords:     "employee/passwords",
    registrations: "employee/registrations"
  }

  # ゲストログイン------------------------------------------------------------
  devise_scope :employee do
    post "/employee/guest_sign_in", to: "employee/sessions#new_guest"
  end

  # 管理者ページ----------------------------------------------------------------
  namespace :admin do
    get "top" => "homes#top", as: "top"
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :employees, only: [:index, :show, :edit, :update, :destroy]
    resources :return_comments, only: [:destroy]
    resources :manuals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  # 従業員ページ----------------------------------------------------------------
  root 'public/homes#top'

  scope module: :public do
    post "/homes/guest_sign_in", to: "homes#new_guest"
    resources :employees, only: [:show, :edit, :update]
    resources :comments do
      collection do
        get "search"
      end
    end
    resources :comments , only: [:index, :show, :create, :update, :destroy]
    resources :employees do
      resource :learnings, only: [:index]
    end
    resources :manuals do
      resource :learnings, only: [:create, :destroy, :index]
      collection do
        get "search"
      end
    end
    resources :manuals, only: [:index, :show, :create]
    resources :return_comments, only: [:index]

    get "employee/:id/learnings" => "learnings#employee_index", as: "learnings_employee"
    get "employee/:id/comments" => "comments#employee_comments", as: "comments_employee"
    get "employee/:id/comments/show" => "comments#employee_comments_show", as: "show_comments_employee"
    patch "comments/:id/is_desolved" => "comments#is_desolved", as: "is_desolved_comments"
    post " comments/return_comments_create" => "comments#return_comments_create", as: "create_return_comments"
    get "learnings/:id/is_learned" => "learnings#manual_is_learned", as: "is_learned_manual_learnings"
    patch "learnings/is_learned" => "learnings#is_rearned", as: "is_learned_learnings"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :employee
  belongs_to :manual
  has_many :return_comments, dependent: :destroy

  validates :comment, presence: true

end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :learnings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :return_comments, dependent: :destroy

  validates :name, presence: true
  validates :telephone_number, presence: true

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |employee|
      employee.password = SecureRandom.alphanumeric(10) + [*'a'..'z'].sample(1).join + [*'0'..'9'].sample(1).join
      employee.name = "ゲストユーザー"
      employee.telephone_number = "09090909090"
        # employee.confirmed_ad = Time.now
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :manuals, dependent: :destroy

  validates :name, presence: true

end

app/models/learning.rb
class Learning < ApplicationRecord

  belongs_to :employee
  belongs_to :manual

end

app/models/manual.rb
class Manual < ApplicationRecord

  has_many :learnings, dependent: :destroy
  has_many :employees, through: :learnings
  has_many :comments, dependent: :destroy
  has_many :employees, through: :comments
  belongs_to :genre

  has_one_attached :video

  validates :task_name, presence: true
  validates :video, presence: true

  validate :video_size, :video_type

  def video_size
    if video.blob.byte_size > 60.megabytes
      errors.add(:video, "動画を60MG以内で撮影しなおして下さい（約３分以内）")
    end
  end

  def video_type
    if !"video".in?(video.blob.content_type)
      errors.add(:video, "はmp4またはwebm形式でアップロードしてください")
    end
  end

  def learned?(employee)
    learnings.where(employee_id: employee.id).exists?
  end

end

app/models/return_comment.rb
class ReturnComment < ApplicationRecord

  belongs_to :comment
  belongs_to :employee

  validates :return_comment, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました"
    else
      @genres = Genre.all
      flash[:alert] = "ジャンル名を入力してください"
      render :index
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を更新しました"
    else
      flash[:alert] = "ジャンル名を入力してください"
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      redirect_to admin_genres_path, notice: "削除が完了しました"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/manuals_controller.rb
class Admin::ManualsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @manuals = Manual.all
    @manual = Manual.new
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @manual = Manual.new
    @genres = Genre.all
  end

  def create
    @manual = Manual.new(manual_params)
    if @manual.save && @genre.sava
      redirect_to admin_manuals_path, notice: "マニュアルを投稿しました"
    else
      @manuals = Manual.all
      @genres = Genre.all
      flash[:alert] = "マニュアルの投稿に失敗しました"
      render :index
    end
  end

  def show
    @manual = Manual.find(params[:id])
    @comments = @manual.comments.all
  end

  def edit
    @manual = Manual.find(params[:id])
    @genres = Genre.all
  end

  def update
    @manual = Manual.find(params[:id])
    @genres = Genre.all
    if @manual.update(manual_params)
      redirect_to admin_manual_path(@manual), notice: "マニュアルを更新しました"
    else
      flash[:alert] = "マニュアルの更新に失敗しました"
      @manual = Manual.find(params[:id])
      render :edit
    end
  end

  def destroy
    @manual = Manual.find(params[:id])
    if @manual.destroy
      redirect_to admin_manuals_path, notice: "削除が完了しました"
    end
  end

  private

  def manual_params
    params.require(:manual).permit(:genre_name, :task_name, :description, :is_draft, :genre_id, :video, :re_draft)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  before_action :authenticate_admin!
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/learnings_helper.rb
module Admin::LearningsHelper
end

app/helpers/admin/manuals_helper.rb
module Admin::ManualsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), data: {"turbolinks" => false} %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), data: {"turbolinks" => false} %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), data: {"turbolinks" => false} %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), data: {"turbolinks" => false} %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), data: {"turbolinks" => false} %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post, data: {"turbolinks" => false} %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation", class="notification is-danger">
    <h4>エラーが発生しました。<br>以下ご確認お願いいたします。</h4>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>楽ま～にゅ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <P class ="alert"><%= alert %></P>
      </div>
    <% end %>

    <nav class="navbar is-size-7-mobile", role="navigation", aria-label="main navigation">
        <div class="nafvbar-brand">
          <%= link_to root_path, data: {"turbolinks" => false} do %>
            <%= image_tag "raku_manu.png", :class => "img-logo" %>
          <% end %>
        </div>

        <a class="navbar-burger navbar-end", data-target="menu", role="button", aria-label="menu", aria-expanded="false">
          <span aria-hiddun="true"></span>
          <span aria-hiddun="true"></span>
          <span aria-hiddun="true"></span>
        </a>

        <% if employee_signed_in? %>
        <div id="menu" class="navbar-menu is-size-7-mobile">

          <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable navbar-end">
              <p class="navbar-link">
                メニュー
              </p>
              <div class="navbar-dropdown">
                <p class="navbar-item">
                <%= link_to 'マイページ', employee_path(current_employee.id), class: 'navbar-item', data: {"turbolinks" => false} %>
                </p>
                <p class="navbar-item">
                  <%= link_to 'マニュアル一覧', manuals_path, class: 'navbar-item text-dark', data: {"turbolinks" => false} %>
                </p>
                <p class="navbar-item">
                  <%= link_to "質問一覧", comments_path, class: "navbar-item text-dark", data: {"turbolinks" => false} %>
                </p>
                <hr class="navbar-divider">
                <p class="navbar-item">
                  <%= link_to "ログアウト", destroy_employee_session_path, method: :delete, class: "navbar-item text-dark", data: {"turbolinks" => false} %>
                </p>
              </div>
            </div>
          </div>
        </div>
        <% elsif admin_signed_in? %>
        <div id="menu" class="navbar-menu is-size-7-mobile">
          <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
              <p class="navbar-link">
                メニュー
              </p>
              <div class="navbar-dropdown is-size-7-mobile">
                <p class="navbar-item">
                  <%= link_to '業務一覧', admin_genres_path, class: 'navbar-item', data: {"turbolinks" => false} %>
                </p>
                <p class="navbar-item">
                  <%= link_to 'マニュアル一覧', admin_manuals_path, class: 'navbar-item text-dark', data: {"turbolinks" => false} %>
                </p>
                <p class="navbar-item">
                  <%= link_to "従業員一覧", admin_employees_path, class: "navbar-item text-dark", data: {"turbolinks" => false} %>
                </p>
                <hr class="navbar-divider">
                <p class="navbar-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "navbar-item text-dark", data: {"turbolinks" => false}%>
                </p>
              </div>
            </div>
          </div>
        </div>
        <% else %>
        <div id="menu" class="navbar-menu is-size-7-mobile">
          <div class="navbar-end">
            <p class="navbar-item">
              <%= link_to new_admin_session_path, class: "button is-link is-outlined mr-2 mb-2", data: {"turbolinks" => false} do %>
                <span class="icon">
                  <i class="fa fa-user"></i>
                </span>
                <span>管理者ログイン（テスト閲覧用）</span>
              <% end %>
              <%= link_to employee_guest_sign_in_path, method: :post, class: "button is-warning is-outlined", data: {"turbolinks" => false} do %>
                <span class="icon">
                  <i class="fa fa-user"></i>
                </span>
                <span>従業員ゲストログイン（閲覧用）</span>
              <% end %>
            </p>
            <div class="navbar-item has-dropdown is-hoverable">
              <p class="navbar-link">
                メニュー
              </p>
              <div class="navbar-dropdown">
                <p class="navbar-item">
                  <%= link_to 'マニュアル一覧', manuals_path, class: 'navbar-item text-dark', data: {"turbolinks" => false} %>
              </p>
                <p class="navbar-item">
                  <%= link_to "ログイン", new_employee_session_path, class: 'navbar-item text-dark', data: {"turbolinks" => false} %>
                </p>
                <p class="navbar-item">
                  <%= link_to "新規登録", new_employee_registration_path, class: 'navbar-item text-dark', data: {"turbolinks" => false} %>
                </p>
              </div>
            </div>
          </div>
        </div>
        <% end %>

    </nav>
    <%= yield %>

  </body>
</html>